# Generated by Django 3.0.5 on 2021-02-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
